- hosts: linux
  become: yes
  tasks:
    - name: Create a login user
    user:
      name: "{{ username }}"
      password: '???'
      groups: # Empty by default, here we give it some groups
        - sudo
      state: present
      shell: /bin/bash       # Defaults to /bin/bash
      system: no             # Defaults to no
      createhome: yes        # Defaults to yes
      home: /home/{{ username }}  # Defaults to /home/<username>