- hosts: linux
  become: yes
  tasks:
    - name: install prerequisites
      apt:
        name:
          - docker.io
        update_cache: yes
    - name: install docker-compose
      apt:
        name: 
          - docker-compose
        update_cache: yes